title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://jack580936.github.io/sf-doc

aux_links:
  Template Repository: https://jack580936.github.io/sf-doc
